/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaAdmin;

import conexionPostsgresql.conexion;
import conexionPostsgresql.crud;
import conexionPostsgresql.encrypt;
import getset.variables;
import getset.variables;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventanasParaAdmin.LoginAdministrador;
import ventanasParaAdmin.Menu_administrador;

/**
 *
 * @author oscar
 */
public class ActualizarDatosOpera extends javax.swing.JFrame {

    /**
     * Creates new form AltaOperador
     */
    FondoPanel fondo = new FondoPanel();

    public ActualizarDatosOpera() {

        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        buscarOperador_txt.requestFocus();
        setIconImage(getIconImage());

    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }
    public void limpiar2() {
        buscarOperador_txt.setText(null);
        actualizar_btn.setEnabled(false);
        eliminarOpera_btn.setEnabled(false);
    }

    public void activarBotones() {
        actualizar_btn.setEnabled(true);
        eliminarOpera_btn.setEnabled(true);
    }

    public void limpiar() {
        idOperador_txt.setText(null);
        matriculaOperador_txt.setText(null);
        grado_opera_txt.setText(null);
        nombreOperador_txt.setText(null);
        apellidosOpera_txt.setText(null);
        contrasena_txt.setText(null);
        empleo_opera_txt.setText(null);

    }

    public void hablitarBotones() {
        actualizar_btn.setEnabled(true);
        cancelar_btn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        altaOperador_lb = new javax.swing.JLabel();
        matricula_lb = new javax.swing.JLabel();
        matriculaOperador_txt = new javax.swing.JTextField();
        nombre_lb = new javax.swing.JLabel();
        nombreOperador_txt = new javax.swing.JTextField();
        areadetrabajo_lb = new javax.swing.JLabel();
        grado_opera_txt = new javax.swing.JTextField();
        contraseña_lb = new javax.swing.JLabel();
        contrasena_txt = new javax.swing.JTextField();
        cancelar_btn = new javax.swing.JButton();
        nombre_lb1 = new javax.swing.JLabel();
        apellidosOpera_txt = new javax.swing.JTextField();
        empleo_opera_txt = new javax.swing.JTextField();
        empleo_opera_lb = new javax.swing.JLabel();
        buscar_txt = new javax.swing.JLabel();
        buscarOperador_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        actualizar_btn = new javax.swing.JButton();
        id_lb = new javax.swing.JLabel();
        idOperador_txt = new javax.swing.JTextField();
        eliminarOpera_btn = new javax.swing.JButton();
        login_btn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        altaOperador_lb.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        altaOperador_lb.setText("ACTUALIZAR DATOS DE OPERADOR");
        jPanel1.add(altaOperador_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        matricula_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        matricula_lb.setText("MATRICULA:");
        jPanel1.add(matricula_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        matriculaOperador_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        matriculaOperador_txt.setEnabled(false);
        matriculaOperador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaOperador_txtActionPerformed(evt);
            }
        });
        jPanel1.add(matriculaOperador_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 272, 31));

        nombre_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        nombre_lb.setText("APELLIDOS");
        jPanel1.add(nombre_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        nombreOperador_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombreOperador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreOperador_txtActionPerformed(evt);
            }
        });
        jPanel1.add(nombreOperador_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 272, 31));

        areadetrabajo_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        areadetrabajo_lb.setText("GRADO:");
        jPanel1.add(areadetrabajo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        grado_opera_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        grado_opera_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grado_opera_txtActionPerformed(evt);
            }
        });
        jPanel1.add(grado_opera_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 272, 31));

        contraseña_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        contraseña_lb.setText("CONTRASEÑA:");
        jPanel1.add(contraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        contrasena_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(contrasena_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 270, 31));

        cancelar_btn.setFont(new java.awt.Font("Impact", 0, 17)); // NOI18N
        cancelar_btn.setText("CANCELAR");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 130, -1));

        nombre_lb1.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        nombre_lb1.setText("NOMBRE:");
        jPanel1.add(nombre_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        apellidosOpera_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidosOpera_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosOpera_txtActionPerformed(evt);
            }
        });
        jPanel1.add(apellidosOpera_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 270, 31));

        empleo_opera_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        empleo_opera_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleo_opera_txtActionPerformed(evt);
            }
        });
        jPanel1.add(empleo_opera_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 272, 31));

        empleo_opera_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        empleo_opera_lb.setText("EMPLEO:");
        jPanel1.add(empleo_opera_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        buscar_txt.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        buscar_txt.setText("MATRICULA:");
        jPanel1.add(buscar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 31));

        buscarOperador_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buscarOperador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarOperador_txtActionPerformed(evt);
            }
        });
        jPanel1.add(buscarOperador_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 272, 31));

        buscar_btn.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        buscar_btn.setText("Buscar");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 660, 10));

        actualizar_btn.setFont(new java.awt.Font("Impact", 0, 17)); // NOI18N
        actualizar_btn.setText("ACTUALIZAR DATOS");
        actualizar_btn.setEnabled(false);
        actualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 160, -1));

        id_lb.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        id_lb.setText("ID:");
        jPanel1.add(id_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        idOperador_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idOperador_txt.setEnabled(false);
        idOperador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idOperador_txtActionPerformed(evt);
            }
        });
        jPanel1.add(idOperador_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 272, 31));

        eliminarOpera_btn.setFont(new java.awt.Font("Impact", 0, 17)); // NOI18N
        eliminarOpera_btn.setText("ELIMINAR REGISTRO");
        eliminarOpera_btn.setEnabled(false);
        eliminarOpera_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarOpera_btnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarOpera_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        login_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        login_btn.setText("Inicio");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_btn)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
            // TODO add your handling code here:
            Menu_administrador menuAdministrador = new Menu_administrador();
            menuAdministrador.setVisible(true);
            menuAdministrador.setLocationRelativeTo(null);
            this.setVisible(false);
        }//GEN-LAST:event_cancelar_btnActionPerformed


    private void matriculaOperador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaOperador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaOperador_txtActionPerformed

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed
        grado_opera_txt.requestFocus();
        encrypt encrypt = new encrypt();
        if (buscarOperador_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingresa una matricula");
            limpiar();
            buscarOperador_txt.setText(null);
            actualizar_btn.setEnabled(false);
            eliminarOpera_btn.setEnabled(false);
        } else {
            limpiar();
            crud objcrud = new crud();
            variables var = new variables();
            objcrud.mostar(buscarOperador_txt.getText());
            idOperador_txt.setText(var.getId_opera());
            matriculaOperador_txt.setText(var.getMatricula_opera());
            grado_opera_txt.setText(var.getGrado_opera());
            empleo_opera_txt.setText(var.getEmpleo_opera());
            nombreOperador_txt.setText(var.getNombre_opera());
            apellidosOpera_txt.setText(var.getApellidos_opera());
            contrasena_txt.setText(encrypt.getAESDecrypt(
                    var.getContraseña_opera())
            );
            buscarOperador_txt.setText(null);
            actualizar_btn.setEnabled(true);
            eliminarOpera_btn.setEnabled(true);

            if (matriculaOperador_txt.getText().equals("")
                    || grado_opera_txt.getText().equals("")
                    || nombreOperador_txt.getText().equals("")
                    || apellidosOpera_txt.getText().equals("")
                    || contrasena_txt.getText().equals("") || empleo_opera_txt.getText().equals("")) {
                buscarOperador_txt.setText(null);
                actualizar_btn.setEnabled(false);
                eliminarOpera_btn.setEnabled(false);
            }
        }


    }//GEN-LAST:event_buscar_btnActionPerformed

    private void actualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_btnActionPerformed
        if (matriculaOperador_txt.getText().equals("")
                || grado_opera_txt.getText().equals("")
                || nombreOperador_txt.getText().equals("")
                || apellidosOpera_txt.getText().equals("")
                || contrasena_txt.getText().equals("") || empleo_opera_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos");
            buscarOperador_txt.setText(null);
            actualizar_btn.setEnabled(false);
            eliminarOpera_btn.setEnabled(false);
            limpiar();
        } else {
            encrypt encrypt = new encrypt();
            crud objcrud = new crud();
            variables var = new variables();
            var.setId_opera(idOperador_txt.getText());
            var.setMatricula_opera(matriculaOperador_txt.getText());
            var.setGrado_opera(grado_opera_txt.getText());
            var.setEmpleo_opera(empleo_opera_txt.getText());
            var.setNombre_opera(nombreOperador_txt.getText());
            var.setApellidos_opera(apellidosOpera_txt.getText());
            var.setContraseña_opera(contrasena_txt.getText());

            objcrud.actualizar(var.getId_opera(), var.getMatricula_opera(), var.getGrado_opera(), var.getEmpleo_opera(), var.getNombre_opera(), var.getApellidos_opera(), encrypt.getAES(var.getContraseña_opera()));
            limpiar();
            buscarOperador_txt.setText(null);
            actualizar_btn.setEnabled(false);
            eliminarOpera_btn.setEnabled(false);
        }

    }//GEN-LAST:event_actualizar_btnActionPerformed

    private void idOperador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idOperador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idOperador_txtActionPerformed

    private void eliminarOpera_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarOpera_btnActionPerformed
        crud objcrud = new crud();
        variables var = new variables();
        var.setMatricula_opera(matriculaOperador_txt.getText());
        objcrud.eliminarOpera(var.getMatricula_opera());
        limpiar();
        buscarOperador_txt.setText(null);
        actualizar_btn.setEnabled(false);
        eliminarOpera_btn.setEnabled(false);
    }//GEN-LAST:event_eliminarOpera_btnActionPerformed

    private void nombreOperador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreOperador_txtActionPerformed
        apellidosOpera_txt.requestFocus();
    }//GEN-LAST:event_nombreOperador_txtActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        LoginAdministrador login = new LoginAdministrador();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_btnActionPerformed

    private void buscarOperador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarOperador_txtActionPerformed
        buscar_btn.requestFocus();
        buscar_btn.doClick();
    }//GEN-LAST:event_buscarOperador_txtActionPerformed

    private void empleo_opera_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleo_opera_txtActionPerformed
        nombreOperador_txt.requestFocus();
    }//GEN-LAST:event_empleo_opera_txtActionPerformed

    private void grado_opera_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grado_opera_txtActionPerformed
        empleo_opera_txt.requestFocus();
    }//GEN-LAST:event_grado_opera_txtActionPerformed

    private void apellidosOpera_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosOpera_txtActionPerformed
        contrasena_txt.requestFocus();
    }//GEN-LAST:event_apellidosOpera_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarDatosOpera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_btn;
    private javax.swing.JLabel altaOperador_lb;
    private javax.swing.JTextField apellidosOpera_txt;
    private javax.swing.JLabel areadetrabajo_lb;
    private javax.swing.JTextField buscarOperador_txt;
    public javax.swing.JButton buscar_btn;
    private javax.swing.JLabel buscar_txt;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JTextField contrasena_txt;
    private javax.swing.JLabel contraseña_lb;
    private javax.swing.JButton eliminarOpera_btn;
    private javax.swing.JLabel empleo_opera_lb;
    private javax.swing.JTextField empleo_opera_txt;
    private javax.swing.JTextField grado_opera_txt;
    private javax.swing.JTextField idOperador_txt;
    private javax.swing.JLabel id_lb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton login_btn;
    private javax.swing.JTextField matriculaOperador_txt;
    private javax.swing.JLabel matricula_lb;
    private javax.swing.JTextField nombreOperador_txt;
    private javax.swing.JLabel nombre_lb;
    private javax.swing.JLabel nombre_lb1;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/l.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }

    }
}
