/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaAdmin;

import ventanasParaAdmin.*;
import conexionPostsgresql.conexion;
import conexionPostsgresql.crud;
import conexionPostsgresql.encrypt;
import getset.variables;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author oscar
 */
public class AltaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AltaOperador
     */
    FondoPanel fondo = new FondoPanel();

    public AltaAdmin() {

        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        matriculaadminr_txt.requestFocus();
        setIconImage(getIconImage());

    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }

    public void limpiar() {
        matriculaadminr_txt.setText(null);
        grado_admin_txt.setText(null);
        nombreadmin_txt.setText(null);
        apellidosadmin_txt.setText(null);
        contrasena_txt.setText(null);
        empleo_admin_txt.setText(null);
    }
    crud objcrud = new crud();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        altaOperador_lb = new javax.swing.JLabel();
        matricula_lb = new javax.swing.JLabel();
        matriculaadminr_txt = new javax.swing.JTextField();
        nombre_lb = new javax.swing.JLabel();
        nombreadmin_txt = new javax.swing.JTextField();
        areadetrabajo_lb = new javax.swing.JLabel();
        grado_admin_txt = new javax.swing.JTextField();
        contraseña_lb = new javax.swing.JLabel();
        contrasena_txt = new javax.swing.JTextField();
        agregaradmin_btn = new javax.swing.JButton();
        nombre_lb1 = new javax.swing.JLabel();
        apellidosadmin_txt = new javax.swing.JTextField();
        empleo_admin_txt = new javax.swing.JTextField();
        empleo_opera_lb = new javax.swing.JLabel();
        login_btn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        altaOperador_lb.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        altaOperador_lb.setText("ALTA DE ADMINISTRADOR");
        jPanel1.add(altaOperador_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        matricula_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        matricula_lb.setText("MATRICULA:");
        jPanel1.add(matricula_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        matriculaadminr_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        matriculaadminr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaadminr_txtActionPerformed(evt);
            }
        });
        jPanel1.add(matriculaadminr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 272, 31));

        nombre_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        nombre_lb.setText("APELLIDOS:");
        jPanel1.add(nombre_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        nombreadmin_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombreadmin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreadmin_txtActionPerformed(evt);
            }
        });
        jPanel1.add(nombreadmin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 272, 31));

        areadetrabajo_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        areadetrabajo_lb.setText("GRADO:");
        jPanel1.add(areadetrabajo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        grado_admin_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        grado_admin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grado_admin_txtActionPerformed(evt);
            }
        });
        jPanel1.add(grado_admin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 272, 31));

        contraseña_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        contraseña_lb.setText("CONTRASEÑA:");
        jPanel1.add(contraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        contrasena_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contrasena_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena_txtActionPerformed(evt);
            }
        });
        jPanel1.add(contrasena_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 270, 31));

        agregaradmin_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        agregaradmin_btn.setText("AÑADIR ADMINISTRADOR");
        agregaradmin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaradmin_btnActionPerformed(evt);
            }
        });
        jPanel1.add(agregaradmin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        nombre_lb1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        nombre_lb1.setText("NOMBRE:");
        jPanel1.add(nombre_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        apellidosadmin_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidosadmin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosadmin_txtActionPerformed(evt);
            }
        });
        jPanel1.add(apellidosadmin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 31));

        empleo_admin_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        empleo_admin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleo_admin_txtActionPerformed(evt);
            }
        });
        jPanel1.add(empleo_admin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 272, 31));

        empleo_opera_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        empleo_opera_lb.setText("EMPLEO:");
        jPanel1.add(empleo_opera_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        login_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        login_btn.setText("Inicio");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_btn)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void agregaradmin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaradmin_btnActionPerformed
            encrypt encript = new encrypt();
            if (matriculaadminr_txt.getText().equals("")
                    || grado_admin_txt.getText().equals("")
                    || nombreadmin_txt.getText().equals("")
                    || apellidosadmin_txt.getText().equals("")
                    || contrasena_txt.getText().equals("") || empleo_admin_txt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debes llenar todos los campos");
            } else {
                objcrud.insertar2(matriculaadminr_txt.getText(), grado_admin_txt.getText(), empleo_admin_txt.getText(), nombreadmin_txt.getText(), apellidosadmin_txt.getText(), encript.getAES(contrasena_txt.getText()));
                this.setVisible(false);
                LoginAdministrador loginAdministrador = new LoginAdministrador();
                loginAdministrador.setVisible(true);
                loginAdministrador.setLocationRelativeTo(null);
                //AltaAdmin altaAdmin = new AltaAdmin();
                //altaAdmin.setVisible(true);
                //altaAdmin.setLocationRelativeTo(null);
                limpiar();
            }

        }//GEN-LAST:event_agregaradmin_btnActionPerformed

    crud crud = new crud();
    variables var = new variables();

    private void matriculaadminr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaadminr_txtActionPerformed
        grado_admin_txt.requestFocus();
    }//GEN-LAST:event_matriculaadminr_txtActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        LoginAdministrador login = new LoginAdministrador();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_btnActionPerformed

    private void grado_admin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grado_admin_txtActionPerformed
        empleo_admin_txt.requestFocus();
    }//GEN-LAST:event_grado_admin_txtActionPerformed

    private void empleo_admin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleo_admin_txtActionPerformed
        nombreadmin_txt.requestFocus();
    }//GEN-LAST:event_empleo_admin_txtActionPerformed

    private void nombreadmin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreadmin_txtActionPerformed
        apellidosadmin_txt.requestFocus();
    }//GEN-LAST:event_nombreadmin_txtActionPerformed

    private void apellidosadmin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosadmin_txtActionPerformed
        contrasena_txt.requestFocus();
    }//GEN-LAST:event_apellidosadmin_txtActionPerformed

    private void contrasena_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena_txtActionPerformed
        agregaradmin_btn.requestFocus();
        agregaradmin_btn.doClick();
    }//GEN-LAST:event_contrasena_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregaradmin_btn;
    private javax.swing.JLabel altaOperador_lb;
    private javax.swing.JTextField apellidosadmin_txt;
    private javax.swing.JLabel areadetrabajo_lb;
    private javax.swing.JTextField contrasena_txt;
    private javax.swing.JLabel contraseña_lb;
    private javax.swing.JTextField empleo_admin_txt;
    private javax.swing.JLabel empleo_opera_lb;
    private javax.swing.JTextField grado_admin_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton login_btn;
    private javax.swing.JLabel matricula_lb;
    private javax.swing.JTextField matriculaadminr_txt;
    private javax.swing.JLabel nombre_lb;
    private javax.swing.JLabel nombre_lb1;
    private javax.swing.JTextField nombreadmin_txt;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/b.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
