/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaAdmin;

import conexionPostsgresql.conexion;
import conexionPostsgresql.crud;
import conexionPostsgresql.encrypt;
import getset.variables;
import getset.variables;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author oscar
 */
public class CambiarContraOpera extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaOperador
     */
    FondoPanel fondo = new FondoPanel();

    public CambiarContraOpera() {

        this.setContentPane(fondo);
        initComponents();

        variables var = new variables();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());

    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }
    java.sql.Statement st;
    ResultSet rs;
    variables var = new variables();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo0 = new javax.swing.JLabel();
        ingresaMatricula_lb = new javax.swing.JLabel();
        cambiarContra_txt = new javax.swing.JTextField();
        cancelar_btn = new javax.swing.JButton();
        cambiarContra_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo0.setText("NUEVA CONTRASEÑA");
        jPanel1.add(titulo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        ingresaMatricula_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        ingresaMatricula_lb.setText("Ingresa la nueva contraseña  de la cuenta: ");
        jPanel1.add(ingresaMatricula_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 468, 60));

        cambiarContra_txt.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cambiarContra_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContra_txtActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarContra_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 450, 40));

        cancelar_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cancelar_btn.setText("CANCELAR");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        cambiarContra_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cambiarContra_btn.setText("CAMBIAR CONTRASEÑA");
        cambiarContra_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContra_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarContra_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
            // TODO add your handling code here:
            Menu_administrador menuAdministrador = new Menu_administrador();
            menuAdministrador.setVisible(true);
            menuAdministrador.setLocationRelativeTo(null);
            this.setVisible(false);
        }//GEN-LAST:event_cancelar_btnActionPerformed

        private void cambiarContra_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContra_txtActionPerformed
            cambiarContra_btn.requestFocus();
            cambiarContra_btn.doClick();
        }//GEN-LAST:event_cambiarContra_txtActionPerformed

    private void cambiarContra_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContra_btnActionPerformed
        if (cambiarContra_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes ingresar una contraseña");
        } else {
            variables var = new variables();
            LoginAdministrador login = new LoginAdministrador();
            String contrasena = cambiarContra_txt.getText();
            encrypt encript = new encrypt();

            try {
                conexion conect = new conexion();
                Connection conexion = conect.conectar();
                st = conexion.createStatement();
                String sql = "UPDATE operador SET cambiar_contra='2', contrasena_opera='" + encript.getAES(contrasena) + "' WHERE matricula_opera = '" + login.matriculaStatic + "';";
                st.executeUpdate(sql);
                st.close();
                conexion.close();
                JOptionPane.showMessageDialog(null, "Se actualizó correctamente la contraseña", "Actualización correcta", JOptionPane.INFORMATION_MESSAGE);
                login.setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se actualizo la contraseña", "Actualización erronea", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_cambiarContra_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraOpera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContra_btn;
    private javax.swing.JTextField cambiarContra_txt;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JLabel ingresaMatricula_lb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo0;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/f.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

}
