/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaAdmin;

import conexionPostsgresql.crud;
import conexionPostsgresql.encrypt;
import getset.variables;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author oscar
 */
public class ConsultaOperador extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaOperador
     */
    FondoPanel fondo = new FondoPanel();

    public ConsultaOperador() {

        this.setContentPane(fondo);
        initComponents();

        variables var = new variables();
        var.mostrarOpera(tablaOpera_table);
        this.setLocationRelativeTo(null);
        MatriculaConsulta_txt.requestFocus();
        setIconImage(getIconImage());
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresaMatricula_lb = new javax.swing.JLabel();
        MatriculaConsulta_txt = new javax.swing.JTextField();
        cancelar_btn = new javax.swing.JButton();
        buscar_btn = new javax.swing.JButton();
        mostrarTodos_txt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOpera_table = new javax.swing.JTable();
        login_btn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CONSULTA DE OPERADORES ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        ingresaMatricula_lb.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        ingresaMatricula_lb.setText("Ingresa la matricula del operador a consultar: ");
        jPanel1.add(ingresaMatricula_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 468, 60));

        MatriculaConsulta_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaConsulta_txtActionPerformed(evt);
            }
        });
        jPanel1.add(MatriculaConsulta_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 315, 30));

        cancelar_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cancelar_btn.setText("CANCELAR");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        buscar_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        buscar_btn.setText("BUSCAR");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        mostrarTodos_txt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        mostrarTodos_txt.setText("MOSTRAR TODOS");
        mostrarTodos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodos_txtActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarTodos_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaOpera_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaOpera_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 590, 270));

        login_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        login_btn.setText("Inicio");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(login_btn)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(login_btn)))
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
            // TODO add your handling code here:
            Menu_administrador menuAdministrador = new Menu_administrador();
            menuAdministrador.setVisible(true);
            menuAdministrador.setLocationRelativeTo(null);
            this.setVisible(false);
        }//GEN-LAST:event_cancelar_btnActionPerformed

        private void MatriculaConsulta_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaConsulta_txtActionPerformed
            buscar_btn.requestFocus();
            buscar_btn.doClick();
        }//GEN-LAST:event_MatriculaConsulta_txtActionPerformed

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed
        //variables var = new variables();
        encrypt encrypt = new encrypt();
        if (MatriculaConsulta_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingresa una matricula");
        } else { 
            crud objcrud = new crud();
            variables var = new variables();
            objcrud.mostar(MatriculaConsulta_txt.getText());
            var.mostrarOpera1(tablaOpera_table, MatriculaConsulta_txt.getText());
            MatriculaConsulta_txt.setText(null);
            
            
            
        }
        
         
    }//GEN-LAST:event_buscar_btnActionPerformed

    private void mostrarTodos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodos_txtActionPerformed
        variables var = new variables();
        var.mostrarOpera(tablaOpera_table);
        MatriculaConsulta_txt.setText(null);
    }//GEN-LAST:event_mostrarTodos_txtActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        LoginAdministrador login = new LoginAdministrador();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaOperador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MatriculaConsulta_txt;
    private javax.swing.JButton buscar_btn;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JLabel ingresaMatricula_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton login_btn;
    private javax.swing.JButton mostrarTodos_txt;
    private javax.swing.JTable tablaOpera_table;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/f.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

}
