/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaOpera;

import ventanasParaOpera.*;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import conexionPostsgresql.conexion;
import conexionPostsgresql.crud;
import ventanasParaAdmin.*;
import ventanasParaOpera.*;
import conexionPostsgresql.crudMaterial;
import conexionPostsgresql.encrypt;
import getset.variables;
import getset.variablesMaterial;
import getset.variablesMaterial;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Embebidos
 */
public class ExtraerMaterial extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    FileInputStream fis;
    int logitudBytes;

    FileInputStream fis2;
    int logitudBytes2;

    conexion conexione = new conexion();
    Connection con = conexione.conectar();
    LoginAdministrador login = new LoginAdministrador();
    public static int cantidad1;
    public static int cantidad2;
    public static int cantidad3;

    /**
     * Creates new form AltaMateriales
     */
    public ExtraerMaterial() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        buscarMaterial_txt.requestFocus();
        setIconImage(getIconImage());
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }

    public void limpiar() {
        Id_txt.setText(null);
        nombre_txt.setText(null);
        descripcion_txt.setText(null);
        cantidad_txt.setText(null);
        unidadMedida_txt.setText(null);
        precio_txt.setText(null);
        noSerie_txt.setText(null);
        noControl_txt.setText(null);
        estadoMaterial_txt.setText(null);
        cantidad_txt.setText(null);
        ubicacion_txt.setText(null);
        observaciones_txt.setText(null);
        factura_txt.setText(null);
        codigoBarras_txt.setText(null);
        label_imagen.setIcon(null);
        areaEntrega.setText(null);
        AreaResibe.setText(null);
        NombreResibe.setText(null);
        gradoResibe.setText(null);
        matriculaResibe.setText(null);
        CantidadASacar.setText(null);

    }
    crudMaterial crudMaterial = new crudMaterial();
    MenuOperador menuOpera = new MenuOperador();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre_l = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descripcion_txt = new javax.swing.JTextField();
        cantidad_l = new javax.swing.JLabel();
        unidadMedida_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precio_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noSerie_l = new javax.swing.JLabel();
        noSerie_txt = new javax.swing.JTextField();
        noControl_l = new javax.swing.JLabel();
        noControl_txt = new javax.swing.JTextField();
        estadoMaterial_l = new javax.swing.JLabel();
        estadoMaterial_txt = new javax.swing.JTextField();
        codigoBarras_l = new javax.swing.JLabel();
        cantidad_txt = new javax.swing.JTextField();
        ubicacion_txt = new javax.swing.JTextField();
        ubicacion_l = new javax.swing.JLabel();
        observaciones_l = new javax.swing.JLabel();
        observaciones_txt = new javax.swing.JTextField();
        factura_l = new javax.swing.JLabel();
        factura_txt = new javax.swing.JTextField();
        codigoBarras_txt = new javax.swing.JTextField();
        buscar_txt = new javax.swing.JLabel();
        buscarMaterial_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        id_l = new javax.swing.JLabel();
        Id_txt = new javax.swing.JTextField();
        label_imagen = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        areaEntrega = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NombreResibe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gradoResibe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        matriculaResibe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AreaResibe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CantidadASacar = new javax.swing.JTextField();
        extraer = new javax.swing.JButton();
        login_btn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        cancelar_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        nombre_l.setText("NOMBRE:");
        jPanel1.add(nombre_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 70, -1));

        nombre_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        nombre_txt.setEnabled(false);
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });
        jPanel1.add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 160, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setText("DESCRIPCIÓN:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

        descripcion_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        descripcion_txt.setEnabled(false);
        descripcion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcion_txtActionPerformed(evt);
            }
        });
        jPanel1.add(descripcion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, -1));

        cantidad_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cantidad_l.setText("CANTIDAD:");
        jPanel1.add(cantidad_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 90, -1));

        unidadMedida_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        unidadMedida_txt.setEnabled(false);
        unidadMedida_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadMedida_txtActionPerformed(evt);
            }
        });
        jPanel1.add(unidadMedida_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 150, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("UNIDAD DE MEDIDA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, -1));

        precio_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        precio_txt.setText(" ");
        precio_txt.setEnabled(false);
        precio_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_txtActionPerformed(evt);
            }
        });
        precio_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precio_txtKeyTyped(evt);
            }
        });
        jPanel1.add(precio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, -1));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setText("PRECIO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        noSerie_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        noSerie_l.setText("NO. SERIE:");
        jPanel1.add(noSerie_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, -1));

        noSerie_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        noSerie_txt.setEnabled(false);
        noSerie_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSerie_txtActionPerformed(evt);
            }
        });
        jPanel1.add(noSerie_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, -1));

        noControl_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        noControl_l.setText("NO. CONTROL:");
        jPanel1.add(noControl_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 110, -1));

        noControl_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        noControl_txt.setEnabled(false);
        jPanel1.add(noControl_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 170, -1));

        estadoMaterial_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        estadoMaterial_l.setText("ESTADO DEL MATERIAL:");
        jPanel1.add(estadoMaterial_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 170, -1));

        estadoMaterial_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        estadoMaterial_txt.setEnabled(false);
        estadoMaterial_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoMaterial_txtActionPerformed(evt);
            }
        });
        jPanel1.add(estadoMaterial_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 240, -1));

        codigoBarras_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        codigoBarras_l.setText("CODIGO DE BARRAS:");
        jPanel1.add(codigoBarras_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, -1));

        cantidad_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        cantidad_txt.setEnabled(false);
        cantidad_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_txtActionPerformed(evt);
            }
        });
        cantidad_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad_txtKeyTyped(evt);
            }
        });
        jPanel1.add(cantidad_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 120, -1));

        ubicacion_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ubicacion_txt.setEnabled(false);
        ubicacion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacion_txtActionPerformed(evt);
            }
        });
        jPanel1.add(ubicacion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 170, -1));

        ubicacion_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ubicacion_l.setText("UBICACIÓN:");
        jPanel1.add(ubicacion_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 90, -1));

        observaciones_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        observaciones_l.setText("OBSERVACIONES: ");
        jPanel1.add(observaciones_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 130, -1));

        observaciones_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        observaciones_txt.setEnabled(false);
        observaciones_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observaciones_txtActionPerformed(evt);
            }
        });
        jPanel1.add(observaciones_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 480, -1));

        factura_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        factura_l.setText("FACTURA:");
        jPanel1.add(factura_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 110, -1));

        factura_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        factura_txt.setEnabled(false);
        factura_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factura_txtActionPerformed(evt);
            }
        });
        jPanel1.add(factura_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 170, -1));

        codigoBarras_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        codigoBarras_txt.setEnabled(false);
        codigoBarras_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarras_txtActionPerformed(evt);
            }
        });
        jPanel1.add(codigoBarras_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, -1));

        buscar_txt.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        buscar_txt.setText("CODIGO DE BARRAS:  ");
        jPanel1.add(buscar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 31));

        buscarMaterial_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buscarMaterial_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaterial_txtActionPerformed(evt);
            }
        });
        jPanel1.add(buscarMaterial_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 272, 31));

        buscar_btn.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        buscar_btn.setText("Buscar");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1280, 10));

        id_l.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        id_l.setText("ID:");
        jPanel1.add(id_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        Id_txt.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Id_txt.setEnabled(false);
        jPanel1.add(Id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        label_imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 190, 200));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1280, 10));

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setText("DATOS DEL SOLICITANTE :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        areaEntrega.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        areaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaEntregaActionPerformed(evt);
            }
        });
        jPanel1.add(areaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setText("AREA QUE ENTREGA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, -1));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setText("NOMBRE COMPLETO DE QUIEN RECIBE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 270, -1));

        NombreResibe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        NombreResibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreResibeActionPerformed(evt);
            }
        });
        jPanel1.add(NombreResibe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 320, -1));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setText("GRADO DE QUIEN RECIBE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 200, -1));

        gradoResibe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        gradoResibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoResibeActionPerformed(evt);
            }
        });
        jPanel1.add(gradoResibe, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 190, -1));

        jLabel10.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel10.setText("MATRICULA DE QUIEN RECIBE:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 220, -1));

        matriculaResibe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        matriculaResibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaResibeActionPerformed(evt);
            }
        });
        jPanel1.add(matriculaResibe, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 220, -1));

        jLabel11.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel11.setText("AREA QUE RECIBE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 150, -1));

        AreaResibe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        AreaResibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaResibeActionPerformed(evt);
            }
        });
        jPanel1.add(AreaResibe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 460, 210, -1));

        jLabel12.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel12.setText("CANTIDAD DEL MATERIAL A EXTRAER:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 260, -1));

        CantidadASacar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CantidadASacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadASacarActionPerformed(evt);
            }
        });
        CantidadASacar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadASacarKeyTyped(evt);
            }
        });
        jPanel1.add(CantidadASacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 100, -1));

        extraer.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        extraer.setText("EXTRAER MATERIAL");
        extraer.setEnabled(false);
        extraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraerActionPerformed(evt);
            }
        });
        jPanel1.add(extraer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, -1, -1));

        login_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        login_btn.setText("Inicio");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        cancelar_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cancelar_btn.setText("CANCELAR");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXTRAER MATERIAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(440, 440, 440)
                                .addComponent(login_btn)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_btn)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcion_txtActionPerformed
        cantidad_txt.requestFocus();
    }//GEN-LAST:event_descripcion_txtActionPerformed


    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed

        areaEntrega.requestFocus();
        if (buscarMaterial_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingresa el codigo de barras de un material");
        } else {
            limpiar();
            crudMaterial objcrud = new crudMaterial();
            variablesMaterial var = new variablesMaterial();
            objcrud.mostar(buscarMaterial_txt.getText());
            Id_txt.setText(var.getId_material());
            nombre_txt.setText(var.getNombre_mate());
            descripcion_txt.setText(var.getDescripcion_mate());
            cantidad_txt.setText(var.getCantidad_mate());
            unidadMedida_txt.setText(var.getUnidad_medidad_mate());
            precio_txt.setText(var.getPrecio_mate());
            noSerie_txt.setText(var.getNoSerie_mate());
            noControl_txt.setText(var.getNoControl_mate());
            estadoMaterial_txt.setText(var.getEstado_mate());
            codigoBarras_txt.setText(var.getcBarras_mate());
            ubicacion_txt.setText(var.getUbicacion_mate());
            observaciones_txt.setText(var.getObservaciones_mate());
            factura_txt.setText(var.getFactura_mate());

            java.sql.Statement st;
            ResultSet rs;
            ImageIcon foto;
            InputStream is;
            ImageIcon foto2;
            InputStream is2;

            try {
                conexion con = new conexion();
                Connection conexion = con.conectar();
                st = conexion.createStatement();
                String sql = "SELECT * FROM material WHERE cBarras_mate = '" + buscarMaterial_txt.getText() + "';";
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    is = rs.getBinaryStream(19);
                    BufferedImage bi = ImageIO.read(is);
                    foto = new ImageIcon(bi);
                    Image img = foto.getImage();
                    Image newimg = img.getScaledInstance(190, 200, java.awt.Image.SCALE_SMOOTH);

                    ImageIcon newicon = new ImageIcon(newimg);
                    label_imagen.setIcon(newicon);

                    is2 = rs.getBinaryStream(20);
                    BufferedImage bi2 = ImageIO.read(is2);
                    foto2 = new ImageIcon(bi2);
                    Image img2 = foto2.getImage();
                    Image newimg2 = img2.getScaledInstance(210, 190, java.awt.Image.SCALE_SMOOTH);

                    ImageIcon newicon2 = new ImageIcon(newimg2);
                    extraer.setEnabled(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "exception : " + ex);
            }

            buscarMaterial_txt.setText(null);
            if (nombre_txt.getText().equals("")
                    || descripcion_txt.getText().equals("")
                    || cantidad_txt.getText().equals("")
                    || unidadMedida_txt.getText().equals("")
                    || precio_txt.getText().equals("")
                    || noSerie_txt.getText().equals("")
                    || noControl_txt.getText().equals("")
                    || estadoMaterial_txt.getText().equals("")
                    || codigoBarras_txt.getText().equals("")
                    || ubicacion_txt.getText().equals("")
                    || observaciones_txt.getText().equals("")
                    || factura_txt.getText().equals("")) {
                buscarMaterial_txt.setText(null);
            }

        }
        nombre_txt.requestFocus();
    }//GEN-LAST:event_buscar_btnActionPerformed


    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        LoginAdministrador login = new LoginAdministrador();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_btnActionPerformed


    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        descripcion_txt.requestFocus();
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void buscarMaterial_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaterial_txtActionPerformed
        buscar_btn.requestFocus();
        buscar_btn.doClick();
    }//GEN-LAST:event_buscarMaterial_txtActionPerformed

    private void cantidad_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_txtActionPerformed
        unidadMedida_txt.requestFocus();
    }//GEN-LAST:event_cantidad_txtActionPerformed

    private void unidadMedida_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadMedida_txtActionPerformed
        precio_txt.requestFocus();
    }//GEN-LAST:event_unidadMedida_txtActionPerformed

    private void precio_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_txtActionPerformed
        noSerie_txt.requestFocus();
    }//GEN-LAST:event_precio_txtActionPerformed

    private void noSerie_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSerie_txtActionPerformed
        estadoMaterial_txt.requestFocus();
    }//GEN-LAST:event_noSerie_txtActionPerformed

    private void estadoMaterial_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoMaterial_txtActionPerformed
        codigoBarras_txt.requestFocus();
    }//GEN-LAST:event_estadoMaterial_txtActionPerformed

    private void codigoBarras_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarras_txtActionPerformed
        ubicacion_txt.requestFocus();
    }//GEN-LAST:event_codigoBarras_txtActionPerformed

    private void ubicacion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacion_txtActionPerformed
        observaciones_txt.requestFocus();
    }//GEN-LAST:event_ubicacion_txtActionPerformed

    private void observaciones_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observaciones_txtActionPerformed
        factura_txt.requestFocus();
    }//GEN-LAST:event_observaciones_txtActionPerformed

    private void factura_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factura_txtActionPerformed

    }//GEN-LAST:event_factura_txtActionPerformed

    private void cantidad_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_txtKeyTyped
        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cantidad_txtKeyTyped

    private void precio_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio_txtKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && precio_txt.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_precio_txtKeyTyped

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed

        menuOpera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelar_btnActionPerformed

    private void areaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaEntregaActionPerformed
        NombreResibe.requestFocus();
    }//GEN-LAST:event_areaEntregaActionPerformed

    private void NombreResibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreResibeActionPerformed
        gradoResibe.requestFocus();
    }//GEN-LAST:event_NombreResibeActionPerformed

    private void gradoResibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoResibeActionPerformed
        matriculaResibe.requestFocus();
    }//GEN-LAST:event_gradoResibeActionPerformed

    private void matriculaResibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaResibeActionPerformed
        AreaResibe.requestFocus();
    }//GEN-LAST:event_matriculaResibeActionPerformed

    private void AreaResibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaResibeActionPerformed
        CantidadASacar.requestFocus();
    }//GEN-LAST:event_AreaResibeActionPerformed

    private void CantidadASacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadASacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadASacarActionPerformed


    private void extraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraerActionPerformed
        if (areaEntrega.getText().equals("")
                || AreaResibe.getText().equals("")
                || cantidad_txt.getText().equals("")
                || NombreResibe.getText().equals("")
                || gradoResibe.getText().equals("")
                || matriculaResibe.getText().equals("")
                || noControl_txt.getText().equals("")
                || CantidadASacar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos");
        } else {
            if (Integer.parseInt(CantidadASacar.getText()) > Integer.parseInt(cantidad_txt.getText()) || CantidadASacar.getText().equals("0")) {
                JOptionPane.showMessageDialog(this, "Cantidad de material erronea");
            } else {

                DateTimeFormatter fecha2 = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                System.out.println("yyyy/MM/dd HH:mm:ss-> NUevo " + fecha2.format(LocalDate.now()));

                try {

                    String sql = "INSERT INTO material_extraido(matricula_solicitante, grado_solicitante, nombrecompleto_solicitante, fecha_extraccion,area_entrega, area_recibe,cantidad_extraer_mate, nombre_mate, descripcion_mate,unidad_medidad_mate, precio_mate, noSerie_mate, noControl_mate, estado_mate, cBarras_mate, ubicacion_mate, observaciones_mate, factura_mate) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
                    PreparedStatement ps = conexione.conectar().prepareStatement(sql);
                    ps.setString(1, matriculaResibe.getText());
                    ps.setString(2, gradoResibe.getText());
                    ps.setString(3, NombreResibe.getText());
                    ps.setString(4, fecha2.format(LocalDate.now()));
                    ps.setString(5, areaEntrega.getText());
                    ps.setString(6, AreaResibe.getText());
                    ps.setInt(7, Integer.parseInt(CantidadASacar.getText()));
                    cantidad1 = Integer.parseInt(cantidad_txt.getText());
                    ps.setString(8, nombre_txt.getText());
                    ps.setString(9, descripcion_txt.getText());
                    ps.setString(10, unidadMedida_txt.getText());
                    ps.setDouble(11, Double.parseDouble(precio_txt.getText()));
                    ps.setString(12, noSerie_txt.getText());
                    ps.setString(13, noControl_txt.getText());
                    ps.setString(14, estadoMaterial_txt.getText());
                    ps.setString(15, codigoBarras_txt.getText());
                    ps.setString(16, ubicacion_txt.getText());
                    ps.setString(17, observaciones_txt.getText());
                    ps.setString(18, factura_txt.getText());
                    
                    ps.execute();
                    ps.close();

                    JOptionPane.showMessageDialog(rootPane, "Se guardo correctamente la extracción de 'Material'");

                } catch (SQLException | NumberFormatException | HeadlessException x) {
                    JOptionPane.showMessageDialog(rootPane, "exception 2" + x);
                }

                try {
                    cantidad2 = Integer.parseInt(CantidadASacar.getText());
                    cantidad3 = cantidad1 - cantidad2;
                    System.out.println("Cantidad 1: " + cantidad1);
                    System.out.println("Cantidad 2: " + cantidad2);
                    System.out.println("Cantidad 3: " + cantidad3);

                    String sql1 = "UPDATE material SET cantidad_mate = ? WHERE cBarras_mate ='" + codigoBarras_txt.getText() + "';";
                    PreparedStatement ps1 = conexione.conectar().prepareStatement(sql1);

                    ps1.setInt(1, cantidad3);
                    ps1.execute();
                    ps1.close();
                    actualizacionQR();

                } catch (SQLException | NumberFormatException | HeadlessException x) {
                    JOptionPane.showMessageDialog(rootPane, "exception 2" + x);
                }
                if (cantidad3 == 0) {
                    try {

                        String sql2 = "DELETE from material WHERE cBarras_mate ='" + codigoBarras_txt.getText() + "';";
                        PreparedStatement ps2 = conexione.conectar().prepareStatement(sql2);
                        ps2.execute();
                        ps2.close();
                    } catch (SQLException | NumberFormatException | HeadlessException x) {
                        JOptionPane.showMessageDialog(rootPane, "exception 2" + x);
                    }
                }else{
                }
                limpiar();
            }

            //crudMaterial.insertar(nombre_txt.getText(), descripcion_txt.getText(), cantidad_txt.getText(), unidadMedida_txt.getText(), precio_txt.getText(), noSerie_txt.getText(), noControl_txt.getText(), estadoMaterial_txt.getText(), cantidad_txt.getText(), ubicacion_txt.getText(), observaciones_txt.getText(), factura_txt.getText());
        }
    }//GEN-LAST:event_extraerActionPerformed

    private void CantidadASacarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadASacarKeyTyped
        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_CantidadASacarKeyTyped

    public void generaQR() {
        int size = 1000;
        String FileType = "png";
        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        System.out.println("yyyy/MM/dd HH:mm:ss-> " + fecha.format(LocalDateTime.now()));

        String nombre = nombre_txt.getText();
        String descripcion = descripcion_txt.getText();
        int cantidad = cantidad3;
        String unidadDeMedida = unidadMedida_txt.getText();
        String precio = precio_txt.getText();
        String nSerie = noSerie_txt.getText();
        String nControl = noControl_txt.getText();
        String estadoMaterial = estadoMaterial_txt.getText();
        String codigoBarras = codigoBarras_txt.getText();
        String ubicacion = ubicacion_txt.getText();
        String observaciones = observaciones_txt.getText();
        String factura = factura_txt.getText();
        String fechaI = fecha.format(LocalDateTime.now());

        String codigo = "Nombre: " + nombre + "\n" + " Descripcion: " + descripcion + "\n" + " Cantidad: " + cantidad + "\n"
                + " Unidad De Media: " + unidadDeMedida + "\n" + " Precio: $" + precio + "\n" + " Numero de serie: " + nSerie + "\n"
                + " Numero De Control : " + nControl + "\n" + " Estado de material: " + estadoMaterial + "\n"
                + " Codigo de barras: " + codigoBarras + "\n" + " Ubicacion: " + ubicacion + "\n"
                + " Observaciones: " + observaciones + "\n" + " Factura: " + factura + "\n" + " Fecha: " + fechaI;
        System.out.println(codigo);
        // Elegir la ruta de la imagen
        String filePath = "C:\\Almacen0\\QR";

        // Generar el nombre
        String randonName = nombre_txt.getText() + "_" + codigoBarras_txt.getText();

        // Generar el QR 
        QRCodeWriter qrcode = new QRCodeWriter();
        try {
            BitMatrix matrix = qrcode.encode(codigo, BarcodeFormat.QR_CODE, size, size);
            File f = new File(filePath + "/" + randonName + "." + FileType);
            int matrixWidth = matrix.getWidth();
            BufferedImage image = new BufferedImage(matrixWidth, matrixWidth, BufferedImage.TYPE_INT_RGB);
            image.createGraphics();

            Graphics2D gd = (Graphics2D) image.getGraphics();
            gd.setColor(Color.WHITE); // Fondo
            gd.fillRect(0, 0, size, size);
            gd.setColor(Color.black); // Qr

            for (int b = 0; b < matrixWidth; b++) {
                for (int j = 0; j < matrixWidth; j++) {
                    if (matrix.get(b, j)) {
                        gd.fillRect(b, j, 1, 1);
                    }
                }
            }

            // Mostrar la imagen generada
            ImageIO.write(image, FileType, f);
            fis2 = new FileInputStream(f.getCanonicalFile());
            this.logitudBytes2 = (int) f.getCanonicalFile().length();

        } catch (WriterException | IOException ex) {
            Logger.getLogger(AltaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void actualizacionQR() {
        generaQR();
        try {

            String sql = "UPDATE material SET imagen_qr = ? WHERE cBarras_mate ='" + codigoBarras_txt.getText() + "';";
            PreparedStatement ps = conexione.conectar().prepareStatement(sql);
            ps.setBinaryStream(1, fis2, logitudBytes2);
            ps.execute();
            ps.close();
            //JOptionPane.showMessageDialog(rootPane, "La imagen QR se actualizo correctamente --> ACtualizado");

        } catch (SQLException | NumberFormatException | HeadlessException x) {
            JOptionPane.showMessageDialog(rootPane, "exception 2" + x);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraerMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraerMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraerMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraerMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtraerMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaResibe;
    private javax.swing.JTextField CantidadASacar;
    private javax.swing.JTextField Id_txt;
    private javax.swing.JTextField NombreResibe;
    private javax.swing.JTextField areaEntrega;
    private javax.swing.JTextField buscarMaterial_txt;
    private javax.swing.JButton buscar_btn;
    private javax.swing.JLabel buscar_txt;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JLabel cantidad_l;
    private javax.swing.JTextField cantidad_txt;
    private javax.swing.JLabel codigoBarras_l;
    private javax.swing.JTextField codigoBarras_txt;
    private javax.swing.JTextField descripcion_txt;
    private javax.swing.JLabel estadoMaterial_l;
    private javax.swing.JTextField estadoMaterial_txt;
    private javax.swing.JButton extraer;
    private javax.swing.JLabel factura_l;
    private javax.swing.JTextField factura_txt;
    private javax.swing.JTextField gradoResibe;
    private javax.swing.JLabel id_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JToggleButton login_btn;
    private javax.swing.JTextField matriculaResibe;
    private javax.swing.JLabel noControl_l;
    private javax.swing.JTextField noControl_txt;
    private javax.swing.JLabel noSerie_l;
    private javax.swing.JTextField noSerie_txt;
    private javax.swing.JLabel nombre_l;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JLabel observaciones_l;
    private javax.swing.JTextField observaciones_txt;
    private javax.swing.JTextField precio_txt;
    private javax.swing.JLabel ubicacion_l;
    private javax.swing.JTextField ubicacion_txt;
    private javax.swing.JTextField unidadMedida_txt;
    // End of variables declaration//GEN-END:variables
 class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/c.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

}
