/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasParaOpera;

import imagen_jtable.tabla;
import imagen_jtable.tabla2;
import imagen_jtable.tabla3;
import ventanasParaAdmin.LoginAdministrador;
import ventanasParaAdmin.ConsultaOperador;
import ventanasParaAdmin.AltaOperador;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author oscar
 */
public class MenuOperador extends javax.swing.JFrame {

    /**
     * Creates new form Menu_administrador
     */
    FondoPanel fondo = new FondoPanel();

    public MenuOperador() {

        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        LoginAdministrador login = new LoginAdministrador();
        titulo0_lb.setText(login.nombreOpera + " " + login.apellidosOpera);
        System.out.println(login.gradoOpera);
        System.out.println(login.matriculaOpera);
        System.out.println(login.empleoOpera);
        setIconImage(getIconImage());
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altaPieza_btn = new javax.swing.JButton();
        cambiarPieza_btn = new javax.swing.JButton();
        consultaPieza_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titulo0_lb1 = new javax.swing.JLabel();
        titulo0_lb = new javax.swing.JLabel();
        login_btn = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        consultaPieza_btn1 = new javax.swing.JButton();
        generaReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        altaPieza_btn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        altaPieza_btn.setText("ALTA DE MATERIAL");
        altaPieza_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPieza_btnActionPerformed(evt);
            }
        });

        cambiarPieza_btn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cambiarPieza_btn.setText("ACTUALIZAR DATOS DE MATERAL");
        cambiarPieza_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarPieza_btnActionPerformed(evt);
            }
        });

        consultaPieza_btn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        consultaPieza_btn.setText("CONSULTA DE MATERIAL");
        consultaPieza_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPieza_btnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo0_lb1.setBackground(new java.awt.Color(51, 51, 0));
        titulo0_lb1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        titulo0_lb1.setText("BIENVENIDO AL ALMACEN :");
        jPanel1.add(titulo0_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, -1));

        titulo0_lb.setBackground(new java.awt.Color(51, 51, 0));
        titulo0_lb.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        titulo0_lb.setText("operador");
        jPanel1.add(titulo0_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 12, 300, 40));

        login_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        login_btn.setText("INICIO");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 10, 70, 30));

        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("EXTRAER MATERIAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        consultaPieza_btn1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        consultaPieza_btn1.setText("OPERADORES QUE INGRESARÓN MATERIAL");
        consultaPieza_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPieza_btn1ActionPerformed(evt);
            }
        });

        generaReporte.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        generaReporte.setText("GENERAR REPORTE DE EXTRACCIÓN");
        generaReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultaPieza_btn)
                            .addComponent(altaPieza_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cambiarPieza_btn)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(63, 63, 63))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(generaReporte)
                                .addGap(14, 14, 14))
                            .addComponent(consultaPieza_btn1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaPieza_btn)
                    .addComponent(cambiarPieza_btn))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaPieza_btn)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(consultaPieza_btn1)
                                .addGap(64, 64, 64))
                            .addComponent(generaReporte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void altaPieza_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPieza_btnActionPerformed
            AltaMateriales altaMate = new AltaMateriales();
            altaMate.setVisible(true);
            this.setVisible(false);

        }//GEN-LAST:event_altaPieza_btnActionPerformed

        private void consultaPieza_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPieza_btnActionPerformed

            tabla consultaMaterial = new tabla();
            consultaMaterial.setLocationRelativeTo(null);
            consultaMaterial.setVisible(true);
            this.setVisible(false);

        }//GEN-LAST:event_consultaPieza_btnActionPerformed

        private void cambiarPieza_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarPieza_btnActionPerformed
            ActualizarDatosMateriales actualizarMate = new ActualizarDatosMateriales();
            actualizarMate.setVisible(true);
            this.setVisible(false);


        }//GEN-LAST:event_cambiarPieza_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        LoginAdministrador login = new LoginAdministrador();
        login.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_login_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExtraerMaterial ExtraccionMaterial = new ExtraerMaterial();
        ExtraccionMaterial.setVisible(true);
        ExtraccionMaterial.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultaPieza_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPieza_btn1ActionPerformed
        
            tabla2 consultaMaterial = new tabla2();
            consultaMaterial.setLocationRelativeTo(null);
            consultaMaterial.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_consultaPieza_btn1ActionPerformed

    private void generaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteActionPerformed
         tabla3 reporte = new tabla3();
            reporte.setLocationRelativeTo(null);
            reporte.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_generaReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOperador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaPieza_btn;
    private javax.swing.JButton cambiarPieza_btn;
    private javax.swing.JButton consultaPieza_btn;
    private javax.swing.JButton consultaPieza_btn1;
    private javax.swing.JButton generaReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton login_btn;
    public javax.swing.JLabel titulo0_lb;
    public javax.swing.JLabel titulo0_lb1;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/obb.JPG")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

}
