/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imagen_jtable;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import imagen_jtable.*;
import imagen_jtable.*;
import conexionPostsgresql.conexion;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ventanasParaAdmin.CambiarContraOpera;
import ventanasParaAdmin.LoginAdministrador;
import static ventanasParaAdmin.LoginAdministrador.apellidosAdmin;
import static ventanasParaAdmin.LoginAdministrador.apellidosOpera;
import static ventanasParaAdmin.LoginAdministrador.empleoAdmin;
import static ventanasParaAdmin.LoginAdministrador.empleoOpera;
import static ventanasParaAdmin.LoginAdministrador.gradoAdmin;
import static ventanasParaAdmin.LoginAdministrador.gradoOpera;
import static ventanasParaAdmin.LoginAdministrador.matriculaAdmin;
import static ventanasParaAdmin.LoginAdministrador.matriculaOpera;
import static ventanasParaAdmin.LoginAdministrador.nombreAdmin;
import static ventanasParaAdmin.LoginAdministrador.nombreOpera;
import ventanasParaAdmin.Menu_administrador;
import ventanasParaOpera.MenuOperador;
import ventanasParaOpera.MenuOperador;

/**
 *
 * @author Embebidos
 */
public class tabla3 extends javax.swing.JFrame {

    FileInputStream fis;
    int logitudBytes;

    conexion conexione = new conexion();
    Connection con = conexione.conectar();
    FondoPanel fondo = new FondoPanel();
    LoginAdministrador login = new LoginAdministrador();

    public tabla3() {
        this.setContentPane(fondo);

        initComponents();
        propiedadesTabla();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource ("imagenes/TERMINADO.png"));
        return retValue;
    }

    private void propiedadesTabla() {
        tabla_prueba.setDefaultRenderer(Object.class, new imagenTable());
        String titulos[] = {"Matricula Solicitante", "Nombre Solicitante", "Grado Solicitante", "Fecha de extracción", "C. De barras Material", "Nombre materia", "Descripción", "Cantidad extraida", "Area que entregó", "Area que recibió"};
        DefaultTableModel tm = new DefaultTableModel(null, titulos);

        java.sql.Statement st;
        ResultSet rs;
        try {
            conexion con = new conexion();
            Connection conexion = con.conectar();
            st = conexion.createStatement();
            String sql = "SELECT * FROM material_extraido;";
            rs = st.executeQuery(sql);
            while (rs.next()) {

                tm.addRow(new Object[]{rs.getString(2), rs.getString(4), rs.getString(3), rs.getString(5), rs.getString(16), rs.getString(9), rs.getString(10), rs.getString(8), rs.getString(6), rs.getString(7)});
                tabla_prueba.setRowHeight(50);
                tabla_prueba.setModel(tm);

                //label_imagen.setIcon(newicon);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "exception : " + ex);

        }

    }

    public void limpiar() {
        matriculaSolicitante.setText(null);
        ano_txt.setText(null);
        mes_txt.setText(null);
        dia_txt.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prueba = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cancelar_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        matriculaSolicitante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ano_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mes_txt = new javax.swing.JTextField();
        dia_txt = new javax.swing.JTextField();
        generaReporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_prueba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_prueba.setEnabled(false);
        jScrollPane1.setViewportView(tabla_prueba);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMBEBIDOS © ");

        cancelar_btn.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        cancelar_btn.setText("<< REGREASAR");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENERAR REPORTE");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setText("DATOS DEL REPORTE A GENERAR:");

        matriculaSolicitante.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        matriculaSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaSolicitanteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setText("MATRICULA DE QUIEN SOLICITO LA EXTRACCIÓN :");

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("FECHA EN LA QUE SE REALIZO LA EXTRACCIÓN :");

        ano_txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ano_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ano_txtActionPerformed(evt);
            }
        });
        ano_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ano_txtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setText("MES:");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setText("AÑO:");

        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setText("DIA:");

        mes_txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mes_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_txtActionPerformed(evt);
            }
        });
        mes_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mes_txtKeyTyped(evt);
            }
        });

        dia_txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dia_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia_txtActionPerformed(evt);
            }
        });
        dia_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dia_txtKeyTyped(evt);
            }
        });

        generaReporte.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        generaReporte.setText("GENERAR REPORTE");
        generaReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(430, 430, 430))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ano_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mes_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202)
                        .addComponent(generaReporte)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matriculaSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(matriculaSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generaReporte)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(ano_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(345, 345, 345)
                        .addComponent(cancelar_btn)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        MenuOperador menuOpera = new MenuOperador();
        menuOpera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelar_btnActionPerformed

    private void generaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteActionPerformed
        if (matriculaSolicitante.getText().equals("")
                || ano_txt.getText().equals("")
                || mes_txt.getText().equals("")
                || dia_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos");
        } else {
            String fecha, matricula, fecha2;
            fecha = ano_txt.getText() + "/" + mes_txt.getText() + "/" + dia_txt.getText();
            fecha2 = ano_txt.getText() + "_" + mes_txt.getText() + "_" + dia_txt.getText();
            matricula = matriculaSolicitante.getText();
            Document documento = new Document(PageSize.A4.rotate());
            try {

                String ruta = System.getProperty("user.home");
                System.out.println(ruta);

                

                com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("C:\\Almacen0\\IMAGENPDF\\logo.jpg");
                header.scaleToFit(300, 1000);
                header.setAlignment(Chunk.ALIGN_CENTER);

                Paragraph parrafo = new Paragraph();
                Paragraph parrafo1 = new Paragraph();
                Paragraph parrafo3 = new Paragraph();
                Paragraph parrafo4 = new Paragraph();
                Paragraph parrafo5 = new Paragraph();

                java.sql.Statement st;
                java.sql.Statement st2;
                ResultSet rs;
                ResultSet rs2;

                System.out.println(fecha);
                System.out.println(matricula);
                try {
                    conexion conect = new conexion();
                    Connection conexion = conect.conectar();
                    st = conexion.createStatement();
                    String sql = "SELECT * FROM material_extraido WHERE matricula_solicitante = '" + matricula + "' and fecha_extraccion = '" + fecha + "';";

                    rs = st.executeQuery(sql);

                    if (rs.next()) {
                        PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Downloads/Extracción_" + matricula + "_" + fecha2 + ".pdf"));
                        System.out.println(rs.getString("nombrecompleto_solicitante"));
                        System.out.println(rs.getString("fecha_extraccion"));

                        parrafo3.setAlignment(Paragraph.ALIGN_LEFT);
                        parrafo3.setFont(FontFactory.getFont("Arial", 14, Font.BOLD, BaseColor.DARK_GRAY));
                        parrafo3.add("DATOS DE QUIEN ENTREGA:\n");

                        parrafo.setAlignment(Paragraph.ALIGN_LEFT);
                        parrafo.add("MATRICULA: " + login.matriculaOpera + "\n");
                        parrafo.add("NOMBRE: " + login.nombreOpera + "\n");
                        parrafo.add("GRADO: " + login.gradoOpera + "\n");
                        parrafo.add("FECHA DE EMISION: " + rs.getString("fecha_extraccion") + "\n");
                        parrafo.add("\n\n");

                        parrafo4.setAlignment(Paragraph.ALIGN_LEFT);
                        parrafo4.setFont(FontFactory.getFont("Arial", 14, Font.BOLD, BaseColor.DARK_GRAY));
                        parrafo4.add("DATOS DE QUIEN RECIBE: \n");
                        parrafo.setAlignment(Paragraph.ALIGN_LEFT);
                        parrafo5.add("MATRICULA: " + rs.getString("matricula_solicitante") + " \n");
                        parrafo5.add("NOMBRE: " + rs.getString("nombrecompleto_solicitante") + " \n");
                        parrafo5.add("GRADO: " + rs.getString("grado_solicitante") + " \n");

                        parrafo1.setAlignment(Paragraph.ALIGN_CENTER);
                        parrafo1.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
                        parrafo1.add("EXTRACCIÓN DE MATERIAL \n\n");

                        documento.open();
                        documento.add(header);
                        documento.add(parrafo3);
                        documento.add(parrafo);
                        documento.add(parrafo4);
                        documento.add(parrafo5);
                        documento.add(parrafo1);

                        PdfPTable tabla = new PdfPTable(8);
                        tabla.addCell("Cantidad");
                        tabla.addCell("Nombre");
                        tabla.addCell("Descripción");
                        tabla.addCell("Codigo de barras");
                        tabla.addCell("Precio c/u");
                        tabla.addCell("Estado");
                        tabla.addCell("Area entrega");
                        tabla.addCell("Area resibe");

                        do {

                            tabla.addCell(rs.getString(8));
                            tabla.addCell(rs.getString(9));
                            tabla.addCell(rs.getString(10));
                            tabla.addCell(rs.getString(16));
                            tabla.addCell("$ "+ rs.getString(12));
                            tabla.addCell(rs.getString(15));
                            tabla.addCell(rs.getString(6));
                            tabla.addCell(rs.getString(7));

                        } while (rs.next());
                        documento.add(tabla);

                        Paragraph parrafo2 = new Paragraph();
                        parrafo2.setAlignment(Paragraph.ALIGN_CENTER);
                        parrafo2.setFont(FontFactory.getFont("Montserrat", 12, Font.NORMAL, BaseColor.DARK_GRAY));
                        parrafo2.add("\n\n\n FIRMA DE OPERADOR                                    FIRMA DE SOLICITANTE \n\n");
                        parrafo2.add("_______________________                              _______________________ \n\n");
                        documento.add(parrafo2);
                        JOptionPane.showMessageDialog(null, "Reporte creado.");
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontro registro de la extracción", "Sin registro", JOptionPane.ERROR_MESSAGE);
                        limpiar();

                    }
                    st.close();
                    conexion.close();

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Error en el sistema de busqueda", "Error busqueda", JOptionPane.ERROR_MESSAGE);
                }

                documento.close();
                

            } catch (DocumentException | FileNotFoundException e) {
                System.out.println("Error en PDF " + e);
            } catch (IOException e) {
                System.out.println("Error en la imagen " + e);
            }

        }


    }//GEN-LAST:event_generaReporteActionPerformed

    private void matriculaSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaSolicitanteActionPerformed
        ano_txt.requestFocus();
    }//GEN-LAST:event_matriculaSolicitanteActionPerformed

    private void ano_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ano_txtActionPerformed
        mes_txt.requestFocus();
    }//GEN-LAST:event_ano_txtActionPerformed

    private void mes_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_txtActionPerformed
        dia_txt.requestFocus();
    }//GEN-LAST:event_mes_txtActionPerformed

    private void dia_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia_txtActionPerformed

    private void ano_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ano_txtKeyTyped
        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_ano_txtKeyTyped

    private void mes_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mes_txtKeyTyped
        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_mes_txtKeyTyped

    private void dia_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dia_txtKeyTyped
        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_dia_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabla3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano_txt;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JTextField dia_txt;
    private javax.swing.JButton generaReporte;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField matriculaSolicitante;
    private javax.swing.JTextField mes_txt;
    private javax.swing.JTable tabla_prueba;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/c.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
